name: yellow_snow
description: See where your fellow developers left their mark

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.3.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  draggable_scrollbar: ^0.1.0
  shared_preferences: ^2.0.5
  image: ^3.0.2
  filepicker_windows: ^2.0.0
  easy_localization: ^3.0.0
  awesome_dialog: ^2.0.0-nullsafety.0
  yaml: ^3.1.0
  win32: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/translations/
    - pubspec.yaml
