name: yellow_snow
description: See where your fellow developers left their mark

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  draggable_scrollbar: ^0.0.4
  shared_preferences: ^0.5.12
  image: ^2.1.18
  filepicker_windows: ^1.0.0
  easy_localization: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/translations/